@TELEMETRY_API_HostAddress = http://localhost:5285

GET {{TELEMETRY_API_HostAddress}}/weatherforecast/
Accept: application/json

###


GET http://192.168.105.227/api/testConnection
Accept: application/json

###

GET http://192.168.105.227/api/establishConnection?missionID=1
Accept: application/json