CREATE DATABASE "XMUONPROBE-MISSIONDB";

CREATE TABLE TELEMETRY_MISSIONS
(
    MISSION_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    MISSION_NAME VARCHAR(50),
    MISSION_START_TIMESTAMP TIMESTAMPTZ
);

CREATE TABLE TELEMETRY_RECORDS
(
    RECORD_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    RECORD_MISSION_ID INT REFERENCES TELEMETRY_MISSIONS(MISSION_ID),
    TOTAL_GEIGER_COUNTS INT,
    GEIGER_COUNTS_PER_MINUTE INT,
    GEIGER_DOSE FLOAT,
    TEMPERATURE FLOAT,
    ATM_PRESSURE FLOAT,
    ALTITUDE FLOAT,
    ACCELERATION_X FLOAT,
    ACCELERATION_Y FLOAT,
    ACCELERATION_Z FLOAT,
    GYRO_X FLOAT,
    GYRO_Y FLOAT,
    GYRO_Z FLOAT,
    MAGNETIC_FIELD_X FLOAT,
    MAGNETIC_FIELD_Y FLOAT,
    MAGNETIC_FIELD_Z FLOAT,
    HEADING_DEG FLOAT,
    GYRO_CHIP_TEMPERATURE FLOAT
);

CREATE OR REPLACE PROCEDURE INSERT_MISSION_RECORD(
    _MISSION_NAME VARCHAR(50),
    _MISSION_START_TIMESTAMP TIMESTAMPTZ)
LANGUAGE plpgsql
AS $$
    DECLARE
    BEGIN
        INSERT INTO TELEMETRY_MISSIONS (
             MISSION_NAME,
             MISSION_START_TIMESTAMP
        )
        VALUES (
          _MISSION_NAME,
          _MISSION_START_TIMESTAMP
         );
    END
$$;

CREATE OR REPLACE PROCEDURE LOG_TELEMETRY_RECORD(
    _RECORD_MISSION_ID INT,
    _TOTAL_GEIGER_COUNTS INT,
    _GEIGER_COUNTS_PER_MINUTE INT,
    _TEMPERATURE FLOAT,
    _ATM_PRESSURE FLOAT,
    _ALTITUDE FLOAT,
    _ACCELERATION_X FLOAT,
    _ACCELERATION_Y FLOAT,
    _ACCELERATION_Z FLOAT,
    _GYRO_X FLOAT,
    _GYRO_Y FLOAT,
    _GYRO_Z FLOAT,
    _MAGNETIC_FIELD_X FLOAT,
    _MAGNETIC_FIELD_Y FLOAT,
    _MAGNETIC_FIELD_Z FLOAT,
    _GYRO_CHIP_TEMPERATURE FLOAT)
LANGUAGE plpgsql
AS $$
    DECLARE _GEIGER_DOSE FLOAT; _HEADING_RAD FLOAT; _HEADING_DEG FLOAT;
    BEGIN
        _GEIGER_DOSE := _GEIGER_COUNTS_PER_MINUTE * 0.00812;
        _HEADING_RAD := ATAN2(_MAGNETIC_FIELD_Y, _MAGNETIC_FIELD_X);
        _HEADING_DEG := (_HEADING_RAD * 180) / PI();

        INSERT INTO TELEMETRY_RECORDS
        (
         RECORD_MISSION_ID,
         TOTAL_GEIGER_COUNTS,
         GEIGER_COUNTS_PER_MINUTE,
         GEIGER_DOSE,
         TEMPERATURE,
         ATM_PRESSURE,
         ALTITUDE,
         ACCELERATION_X,
         ACCELERATION_Y,
         ACCELERATION_Z,
         GYRO_X,
         GYRO_Y,
         GYRO_Z,
         MAGNETIC_FIELD_X,
         MAGNETIC_FIELD_Y,
         MAGNETIC_FIELD_Z,
         HEADING_DEG,
         GYRO_CHIP_TEMPERATURE
        )
        VALUES
        (
         _RECORD_MISSION_ID,
         _TOTAL_GEIGER_COUNTS,
         _GEIGER_COUNTS_PER_MINUTE,
         _GEIGER_DOSE,
         _TEMPERATURE,
         _ATM_PRESSURE,
         _ALTITUDE,
         _ACCELERATION_X,
         _ACCELERATION_Y,
         _ACCELERATION_Z,
         _GYRO_X,
         _GYRO_Y,
         _GYRO_Z,
         _MAGNETIC_FIELD_X,
         _MAGNETIC_FIELD_Y,
         _MAGNETIC_FIELD_Z,
         _HEADING_DEG,
         _GYRO_CHIP_TEMPERATURE
        );
    END
$$;

CREATE OR REPLACE VIEW VW_MISSIONS
AS SELECT * FROM TELEMETRY_MISSIONS;

CREATE OR REPLACE PROCEDURE GET_MISSION_DATA(
    MISSION_ID INT,
    INOUT result_set REFCURSOR  -- Add an INOUT parameter for the cursor
)
LANGUAGE plpgsql
AS $$
    DECLARE
    BEGIN
        OPEN result_set FOR
        SELECT total_geiger_counts,
               geiger_counts_per_minute,
               geiger_dose,
               temperature,
               atm_pressure,
               altitude,
               acceleration_x,
               acceleration_y,
               acceleration_z,
               gyro_x,
               gyro_y,
               gyro_z,
               magnetic_field_x,
               magnetic_field_y,
               magnetic_field_z,
               heading_deg,
               gyro_chip_temperature
        FROM TELEMETRY_RECORDS
        WHERE RECORD_MISSION_ID = MISSION_ID;
    END;
$$;

BEGIN TRANSACTION;
CALL GET_MISSION_DATA(1, 'CURSOR');
FETCH ALL FROM "CURSOR";
COMMIT;

SELECT * FROM VW_MISSIONS;

SELECT * FROM TELEMETRY_MISSIONS;
SELECT * FROM TELEMETRY_RECORDS;
SELECT COUNT(*) AS RECORD_COUNT FROM TELEMETRY_RECORDS;