CREATE DATABASE "XMUONPROBE-MISSIONDB";

ALTER TABLE telemetry_missions ADD COLUMN MISSION_ACTIVENESS_STATE BOOLEAN DEFAULT TRUE;

CREATE TABLE TELEMETRY_MISSIONS
(
    MISSION_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    MISSION_NAME VARCHAR(50),
    MISSION_START_TIMESTAMP TIMESTAMPTZ,
    MISSION_ACTIVENESS_STATE BOOLEAN
);

CREATE TABLE TELEMETRY_RECORDS
(
    RECORD_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    RECORD_MISSION_ID INT REFERENCES TELEMETRY_MISSIONS(MISSION_ID),
    RECORD_TIMESTAMP TIMESTAMP DEFAULT now(),
    TOTAL_GEIGER_COUNTS INT,
    GEIGER_COUNTS_PER_MINUTE INT,
    GEIGER_COUNTS_PER_SECOND FLOAT,
    GEIGER_DOSE FLOAT,
    TEMPERATURE FLOAT,
    ATM_PRESSURE FLOAT,
    ALTITUDE FLOAT,
    ACCELERATION_X FLOAT,
    ACCELERATION_Y FLOAT,
    ACCELERATION_Z FLOAT,
    GYRO_X FLOAT,
    GYRO_Y FLOAT,
    GYRO_Z FLOAT,
    MAGNETIC_FIELD_X FLOAT,
    MAGNETIC_FIELD_Y FLOAT,
    MAGNETIC_FIELD_Z FLOAT,
    HEADING_DEG FLOAT,
    GYRO_CHIP_TEMPERATURE FLOAT
);